version: "2"
services:
  app:
    build: ./app
    image: shimo21/flask
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mariadb:10.3.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
